name: Build HiGHSMEX

on:
  workflow_dispatch:
    inputs:
      highs_version:
        description: "HiGHS version to use for MEX build"
        required: true
        default: "1.15.1"
      build_macos:
        required: true
        type: boolean
        default: true
      build_windows:
        required: true
        type: boolean
        default: true

jobs:
  build_macos:
    if: ${{ inputs.build_macos }}
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Build macOS MEX file with HiGHS ${{ inputs.highs_version }}
        uses: ./.github/actions/build-highsmex
        with:
          highs_version: ${{ inputs.highs_version }}

  build_windows:
    if: ${{ inputs.build_windows }}
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Build Windows MEX file with HiGHS ${{ inputs.highs_version }}
        uses: ./.github/actions/build-highsmex
        with:
          highs_version: ${{ inputs.highs_version }}
